project:
  type: website

website:
  title: "Nhu Nguyen — Data & Analytics"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts/welcome/index.qmd
      - text: About
        href: about.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/Amberlynn9

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: false
    smooth-scroll: true




